## KNN Regressor

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
from sklearn.datasets import make_regression

In [4]:
X,y = make_regression(n_samples=1000,n_features=3,noise=10,random_state=42)

In [5]:
X

array([[-0.18912039, -1.33031363,  0.92165011],
       [-0.65332923, -0.47494531,  1.76545424],
       [-0.22485598,  0.07685188, -0.65000258],
       ...,
       [ 1.39020755,  0.8177663 ,  0.55781031],
       [-1.25239344, -0.01208895,  0.36363188],
       [-1.61513182, -0.03564148,  1.16473935]], shape=(1000, 3))

In [6]:
y

array([-9.61827528e+01, -6.02872731e+01, -2.81936820e+01, -1.26971696e+01,
        1.17141487e+01, -3.23911934e+01, -1.20070632e+02, -1.20064805e+02,
        1.14537252e+02, -2.99426757e+00, -1.05438532e+02,  1.14538403e+02,
        1.44838439e+02,  9.68171078e+00, -1.72768051e+01, -5.30198311e+01,
        1.23782919e+02,  1.37567924e+01,  3.03488896e+02, -5.35795026e+01,
        3.82437918e+01, -1.10956037e+02,  2.00471930e+02, -4.93157958e+01,
        1.79125287e+02, -2.71114344e+01, -1.21997200e+02, -3.91726957e+01,
        1.45741308e+02,  1.07485132e+02, -1.49769004e+02,  1.85156190e+02,
        2.56878417e+01,  1.39580321e+02,  1.15834327e+02, -1.32150974e+02,
        8.68707967e+01, -2.44791228e+02, -3.89215932e+01,  2.64075687e+02,
       -2.54337284e+02,  8.56048215e+01, -1.33735595e+02,  1.87907133e+02,
        2.13878684e+01,  1.78953741e+01, -4.14618140e+01,  5.64403021e+01,
        2.44449115e+02,  9.65426950e+01,  2.06713024e+02,  3.12744438e+01,
       -7.27440064e+01, -

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [9]:
X_train

array([[ 0.34648848,  0.91632767,  0.99801011],
       [ 0.55623001,  1.32819414,  0.45588777],
       [ 0.84910211,  0.69553776, -0.29396695],
       ...,
       [-0.6115178 , -0.75538293, -1.4066611 ],
       [ 0.39046485, -0.13737179, -0.10322175],
       [ 0.51443883,  0.12029563,  0.71161488]], shape=(670, 3))

In [10]:
X_test

array([[-5.95661294e-01, -6.53766339e-01,  1.37443809e+00],
       [ 4.20972944e-01,  6.98828420e-01,  4.92018848e-01],
       [-4.88849422e-01,  1.54324353e+00, -1.11961743e+00],
       [ 1.18570415e+00,  5.36652753e-01,  7.18953311e-01],
       [-1.12548905e+00,  2.79968626e-01,  2.44575198e+00],
       [-1.01475673e+00, -5.81680914e-01, -6.49277545e-01],
       [ 1.49072614e+00, -2.13442871e-01,  1.48667457e-01],
       [ 6.02302099e-02, -2.65138754e-02,  2.46324211e+00],
       [-9.60598997e-02,  2.56008454e+00,  1.14927333e+00],
       [-9.95815395e-01, -4.08100839e-01,  6.51136242e-01],
       [-1.41836573e+00,  9.32590832e-01, -1.76080881e+00],
       [ 1.31759754e+00,  1.68460976e-01, -1.00654257e+00],
       [-4.83061052e-01,  8.95038314e-01,  1.46793012e-01],
       [-1.14300491e+00,  6.38730222e-01,  1.63343153e+00],
       [ 1.42730678e-02,  7.30764119e-01, -9.53939419e-01],
       [-9.04316625e-01,  2.59722502e-01,  6.38592459e-01],
       [-2.75149051e-02, -2.87226221e+00

In [11]:
from sklearn.neighbors import KNeighborsRegressor

In [12]:
regressor = KNeighborsRegressor(n_neighbors=5,algorithm='auto')
regressor.fit(X_train,y_train)

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [13]:
y_pred = regressor.predict(X_test)

In [17]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

print("R2 Score: ",r2_score(y_test,y_pred))
print("Mean Absolute Error: ",mean_absolute_error(y_test,y_pred))
print("Mean Squared Error: ",mean_squared_error(y_test,y_pred))



R2 Score:  0.966927347300765
Mean Absolute Error:  17.13989188394389
Mean Squared Error:  543.1828481001586
