In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
from sklearn.datasets import make_classification

X,y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=15)

In [4]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [5]:
from sklearn.linear_model import LogisticRegression
regression=LogisticRegression()
regression.fit(X_train,y_train)
y_pred=regression.predict(X_test)
print(y_pred)

[0 0 0 1 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 0 1
 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0
 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 1
 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 1 1 0 0 0 1 1
 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0 1 0 1 0
 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 0 1
 0 0 1 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 1
 0 1 0 0]


In [6]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
score = accuracy_score(y_test,y_pred)
print("Accuracy Score is: ",score)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy Score is:  0.9166666666666666
[[146  11]
 [ 14 129]]
              precision    recall  f1-score   support

           0       0.91      0.93      0.92       157
           1       0.92      0.90      0.91       143

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300



# Hyperparameter Tuning and Cross Validation

## Grid Search CV(Cross Validation)

In [7]:
model=LogisticRegression()
penalty=['l1', 'l2', 'elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

In [8]:
params=dict(penalty=penalty,C=c_values,solver=solver)

In [9]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()

In [10]:
## GridSearchCV
from sklearn.model_selection import GridSearchCV

grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [11]:
grid

,estimator,LogisticRegression()
,param_grid,"{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['newton-cg', 'lbfgs', ...]}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l2'


In [12]:
grid.fit(X_train,y_train)

c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\linear_model\_logi

,estimator,LogisticRegression()
,param_grid,"{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['newton-cg', 'lbfgs', ...]}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l1'


In [13]:
grid.get_params

<bound method BaseEstimator.get_params of GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')>

In [14]:
grid.best_params_

{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}

In [15]:
grid.best_score_

np.float64(0.9242857142857142)

In [16]:
y_pred = grid.predict(X_test)

In [17]:
score = accuracy_score(y_test,y_pred)
print(score)
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_test,y_pred))

0.92
              precision    recall  f1-score   support

           0       0.95      0.90      0.93       165
           1       0.89      0.94      0.91       135

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

[[149   8]
 [ 16 127]]


# Random Search CV


In [18]:
from sklearn.model_selection import RandomizedSearchCV


In [19]:
model = LogisticRegression()
randomcv = RandomizedSearchCV(estimator=LogisticRegression(),param_distributions=params,scoring='accuracy',cv=5)

In [20]:
randomcv.fit(X_train,y_train)

c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn

,estimator,LogisticRegression()
,param_distributions,"{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['newton-cg', 'lbfgs', ...]}"
,n_iter,10
,scoring,'accuracy'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [21]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l1', 'C': 0.1}

In [22]:
randomcv.best_score_

np.float64(0.9214285714285714)

In [23]:
y_pred = randomcv.predict(X_test)

In [24]:
score = accuracy_score(y_test,y_pred)

In [25]:
print(score)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9166666666666666


              precision    recall  f1-score   support

           0       0.91      0.94      0.92       157
           1       0.93      0.90      0.91       143

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

[[147  10]
 [ 15 128]]


# Logistic Regression for Multiclass Classification problem

In [26]:
X,y =make_classification(n_samples=1000,n_features=20,n_classes=3,n_informative=3,random_state=15)

In [27]:
y

array([2, 0, 0, 1, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 0, 1, 2, 0, 1, 1, 2, 1,
       1, 1, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0, 0, 1, 0, 1, 2, 1, 2, 0, 0, 0,
       1, 2, 2, 0, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 2, 2, 2, 0, 1, 1, 1, 2,
       0, 1, 1, 1, 0, 2, 0, 0, 1, 0, 0, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 1,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 2, 2, 1, 2, 2, 1, 2, 2, 0, 0, 2, 2,
       1, 1, 2, 2, 0, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 1, 0, 2, 1, 1, 2,
       1, 1, 2, 1, 2, 2, 0, 1, 0, 2, 2, 0, 1, 1, 0, 2, 2, 1, 1, 2, 0, 2,
       1, 2, 1, 1, 2, 2, 1, 0, 1, 2, 1, 0, 0, 2, 2, 1, 0, 2, 2, 0, 2, 1,
       2, 0, 0, 1, 0, 1, 0, 2, 2, 1, 1, 0, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2,
       2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 1, 2, 1, 0, 0, 0, 0, 1, 1, 2, 2, 2,
       1, 0, 2, 2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 0, 0, 0, 2, 1, 1, 0, 2, 0,
       2, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 0, 0, 2, 0, 0, 1, 0,
       1, 1, 2, 0, 2, 0, 1, 2, 0, 0, 1, 2, 2, 0, 2, 0, 0, 1, 0, 1, 0, 1,
       2, 2, 0, 0, 2, 1, 0, 1, 1, 1, 2, 0, 0, 0, 2,

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [29]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(multi_class='ovr')
logistic.fit(X_train,y_train)
y_pred = logistic.predict(X_test)

c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [30]:
y_pred

array([0, 1, 2, 1, 0, 2, 0, 0, 2, 2, 1, 0, 1, 0, 2, 2, 1, 1, 2, 1, 0, 2,
       2, 2, 1, 0, 1, 2, 2, 0, 0, 1, 1, 1, 0, 2, 0, 0, 2, 2, 0, 0, 1, 0,
       0, 1, 2, 2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 1, 2, 1, 0, 2, 2, 1,
       2, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 2, 2, 2, 0,
       0, 1, 1, 0, 0, 2, 2, 1, 2, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 1, 1, 0, 1, 0, 2, 0, 2, 2, 0, 2, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 2, 0, 0, 2, 0, 1, 2, 0, 2,
       0, 1, 2, 0, 2, 2, 1, 2, 1, 2, 0, 2, 0, 2, 2, 2, 2, 0, 1, 2, 2, 1,
       2, 2, 1, 2, 2, 0, 2, 0, 2, 2, 2, 1, 0, 1, 0, 2, 2, 1, 0, 1, 2, 1,
       2, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 2, 1, 2, 1, 2, 0, 0, 2, 0, 0, 2, 2, 0, 2,
       0, 0, 0, 2, 2, 0, 0, 2, 0, 1, 0, 1, 0, 0, 1, 1, 2, 0, 0, 0, 1, 2,
       2, 1, 1, 2, 2, 2, 1, 1, 1, 0, 0, 0, 1, 0, 2, 1, 0, 1, 0, 2, 0, 2,
       2, 0, 0, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 2])

In [31]:
score = accuracy_score(y_test,y_pred)
print(score)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.81
              precision    recall  f1-score   support

           0       0.85      0.84      0.85       114
           1       0.80      0.77      0.78        92
           2       0.78      0.81      0.79        94

    accuracy                           0.81       300
   macro avg       0.81      0.81      0.81       300
weighted avg       0.81      0.81      0.81       300

[[96 13  5]
 [ 4 71 17]
 [13  5 76]]


# logistic Regression for imbalanced Regression

In [32]:
from collections import Counter
from sklearn.datasets import make_classification


In [33]:
X,y = make_classification(n_samples=10000,n_features=2,n_clusters_per_class=1,n_redundant=0,weights=[0.99],random_state=10)

In [34]:
X

array([[ 1.87991016, -1.4850347 ],
       [ 0.37708311, -2.23858488],
       [ 1.35431163, -2.66463822],
       ...,
       [ 0.99509904, -0.54192355],
       [ 1.75859359, -1.54961188],
       [ 0.79770543, -1.99467372]], shape=(10000, 2))

In [36]:
Counter(y)

Counter({np.int64(0): 9846, np.int64(1): 154})

In [37]:
import seaborn as sns

In [38]:
import pandas as pd
sns.scatterplot(pd.DataFrame(X)[0],pd.DataFrame(X)[1],hue=y)

TypeError: scatterplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [42]:
class_weight = [{0:w,1:y} for w in [1,10,50,100] for y in [1,10,50,100]]

In [43]:
class_weight

[{0: 1, 1: 1},
 {0: 1, 1: 10},
 {0: 1, 1: 50},
 {0: 1, 1: 100},
 {0: 10, 1: 1},
 {0: 10, 1: 10},
 {0: 10, 1: 50},
 {0: 10, 1: 100},
 {0: 50, 1: 1},
 {0: 50, 1: 10},
 {0: 50, 1: 50},
 {0: 50, 1: 100},
 {0: 100, 1: 1},
 {0: 100, 1: 10},
 {0: 100, 1: 50},
 {0: 100, 1: 100}]

In [44]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
penalty = ['l1','l2','elasticnet']
c_values = [100,10,1.0,0.1,0.01]
solver = ['newton-cg','lbfgs','liblinear','sag','saga']
class_weight = [{0:w,1:y} for w in [1,10,50,100] for y in [1,10,50,100]]

In [45]:
parms = dict(penalty=penalty,C=c_values,solver=solver,class_weight=class_weight)

In [46]:
parms

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
 'class_weight': [{0: 1, 1: 1},
  {0: 1, 1: 10},
  {0: 1, 1: 50},
  {0: 1, 1: 100},
  {0: 10, 1: 1},
  {0: 10, 1: 10},
  {0: 10, 1: 50},
  {0: 10, 1: 100},
  {0: 50, 1: 1},
  {0: 50, 1: 10},
  {0: 50, 1: 50},
  {0: 50, 1: 100},
  {0: 100, 1: 1},
  {0: 100, 1: 10},
  {0: 100, 1: 50},
  {0: 100, 1: 100}]}

In [47]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()
grid = GridSearchCV(estimator=model,param_grid=parms,scoring='accuracy',cv=cv)

In [48]:
grid.fit(X_train,y_train)

c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\abhin\DataScience_ML\venv\Lib\site-packages\sklearn

,estimator,LogisticRegression()
,param_grid,"{'C': [100, 10, ...], 'class_weight': [{0: 1, 1: 1}, {0: 1, 1: 10}, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['newton-cg', 'lbfgs', ...]}"
,scoring,'accuracy'
,n_jobs,None
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l2'


In [49]:
grid.best_params_

{'C': 0.01,
 'class_weight': {0: 10, 1: 50},
 'penalty': 'l2',
 'solver': 'newton-cg'}

In [50]:
grid.best_score_

np.float64(0.9881333333333334)

In [51]:
y_pred = grid.predict(X_test)

In [52]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


In [53]:
score = accuracy_score(y_test,y_pred)

In [54]:
print(score)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.992
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      2470
           1       0.86      0.40      0.55        30

    accuracy                           0.99      2500
   macro avg       0.92      0.70      0.77      2500
weighted avg       0.99      0.99      0.99      2500

[[2468    2]
 [  18   12]]


# Logistic Regression With ROC curve And ROC AUC score